from automesh import Spn

nel = [4, 5, 3]
scale = [1, 1, 1]
translate = [0, 0, 0]


def test_write_inp():
    spn = Spn.from_spn('tests/input/f.spn', nel)
    fem = spn.as_finite_elements(scale, translate)
    fem.write_inp('target/f.inp')
    with open('tests/input/f.inp') as gold, open('target/f.inp') as file:
        for _ in range(2):
            assert gold.readline() == file.readline()
        gold.readline()
        assert file.readline()[:8] == "version "
        # not checking version number
        gold.readline()
        assert file.readline()[:17] == "autogenerated on "
        line = file.readline()
        while line != '':
            assert gold.readline() == line
            line = file.readline()
